sonar.projectKey=capstone
sonar.projectName=capstone
sonar.sources=api,database,config
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,database/migrations/**,**/.venv/**
sonar.sourceEncoding=UTF-8
